<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-01T15:07:58 IST" name="Default suite" finished-at="2024-08-01T15:07:59 IST" duration-ms="240">
    <groups>
    </groups>
    <test started-at="2024-08-01T15:07:58 IST" name="Default test" finished-at="2024-08-01T15:07:59 IST" duration-ms="240">
      <class name="com.testng.DependsOn_Test">
        <test-method signature="roll()[pri:2, instance:com.testng.DependsOn_Test@5b1669c0]" started-at="2024-08-01T15:07:59 IST" name="roll" finished-at="2024-08-01T15:07:59 IST" depends-on-methods="dependsn_Test.DependsOn2_Test.signin" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- roll -->
        <test-method signature="pay()[pri:4, instance:com.testng.DependsOn_Test@5b1669c0]" started-at="2024-08-01T15:07:59 IST" name="pay" finished-at="2024-08-01T15:07:59 IST" depends-on-methods="com.testng.DependsOn_Test.roll" duration-ms="3" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at com.testng.DependsOn_Test.pay(DependsOn_Test.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pay -->
        <test-method signature="signout()[pri:3, instance:com.testng.DependsOn_Test@5b1669c0]" started-at="2024-08-01T15:07:59 IST" name="signout" finished-at="2024-08-01T15:07:59 IST" depends-on-methods="com.testng.DependsOn_Test.pay" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.testng.DependsOn_Test.signout() on instance com.testng.DependsOn_Test@5b1669c0 depends on not successfully finished methods 
[com.testng.DependsOn_Test.pay() on instance com.testng.DependsOn_Test@5b1669c0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.testng.DependsOn_Test.signout() on instance com.testng.DependsOn_Test@5b1669c0 depends on not successfully finished methods 
[com.testng.DependsOn_Test.pay() on instance com.testng.DependsOn_Test@5b1669c0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signout -->
      </class> <!-- com.testng.DependsOn_Test -->
      <class name="dependsn_Test.DependsOn2_Test">
        <test-method signature="signin()[pri:4, instance:dependsn_Test.DependsOn2_Test@543295b0]" started-at="2024-08-01T15:07:59 IST" name="signin" finished-at="2024-08-01T15:07:59 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signin -->
      </class> <!-- dependsn_Test.DependsOn2_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
